x="  ';';';rcv academy rcv academy rcv academy rcv academy 666"
y=9494424399
#print(y.find(73))
print(len(x))
print(str(y))
z=str(y)
print(z.find("73"))
a=x.upper()
print(x.upper())
print(x.count("rcv",10,30))
print(a.isupper())
print(a.islower())
print(x.split())
print(x.lstrip(';7 \''))
print(x.rstrip(';7 \''))
print(x.replace("rcv","stm",2))
print(x.find("rcv"))
print(x.index("rcv"))